/**
 * Weekly goals — generated by Cloud Function on Monday, tracked locally.
 * 3 goals per week, personalized based on user data.
 */
import type { SQLiteDatabase } from 'expo-sqlite';

export interface WeeklyGoal {
  id?: number;
  weekStart: string;
  goalText: string;
  goalType: string;
  targetCount: number;
  currentCount: number;
  completed: boolean;
}

/** Get current week start (Monday) as ISO date */
function getWeekStart(): string {
  const now = new Date();
  const day = now.getDay();
  const diff = now.getDate() - day + (day === 0 ? -6 : 1); // Monday
  const monday = new Date(now.setDate(diff));
  return monday.toISOString().split('T')[0];
}

/** Get goals for the current week */
export async function getCurrentGoals(db: SQLiteDatabase): Promise<WeeklyGoal[]> {
  const weekStart = getWeekStart();
  const rows = await db.getAllAsync<{
    id: number;
    week_start: string;
    goal_text: string;
    goal_type: string;
    target_count: number;
    current_count: number;
    completed: number;
  }>(`SELECT * FROM weekly_goals WHERE week_start = ? ORDER BY id`, [weekStart]);

  return rows.map((row) => ({
    id: row.id,
    weekStart: row.week_start,
    goalText: row.goal_text,
    goalType: row.goal_type,
    targetCount: row.target_count,
    currentCount: row.current_count,
    completed: row.completed === 1,
  }));
}

/** Save goals from Cloud Function to SQLite */
export async function saveGoals(
  db: SQLiteDatabase,
  goals: Array<{ text: string; type: string; targetCount: number }>,
): Promise<void> {
  const weekStart = getWeekStart();

  // Don't overwrite existing goals for this week
  const existing = await db.getFirstAsync<{ count: number }>(
    `SELECT COUNT(*) as count FROM weekly_goals WHERE week_start = ?`,
    [weekStart],
  );
  if ((existing?.count ?? 0) > 0) return;

  for (const goal of goals) {
    await db.runAsync(
      `INSERT INTO weekly_goals (week_start, goal_text, goal_type, target_count, current_count, completed, created_at)
       VALUES (?, ?, ?, ?, 0, 0, datetime('now'))`,
      [weekStart, goal.text, goal.type, goal.targetCount],
    );
  }
}

/** Increment progress on a goal */
export async function incrementGoalProgress(
  db: SQLiteDatabase,
  goalId: number,
): Promise<void> {
  await db.runAsync(
    `UPDATE weekly_goals SET current_count = MIN(current_count + 1, target_count),
     completed = CASE WHEN current_count + 1 >= target_count THEN 1 ELSE 0 END
     WHERE id = ?`,
    [goalId],
  );
}

/** Generate default goals when Cloud Function is unavailable (offline fallback) */
export async function generateDefaultGoals(db: SQLiteDatabase): Promise<void> {
  const defaults = [
    { text: 'Talk to Maa 3 times this week', type: 'voice', targetCount: 3 },
    { text: 'Log your mood today', type: 'mood', targetCount: 1 },
    { text: 'Track your sleep for 5 days', type: 'sleep', targetCount: 5 },
  ];
  await saveGoals(db, defaults);
}
