/**
 * Weekly goals — generated by Cloud Function on Monday, tracked locally.
 * 3 goals per week, personalized based on user data.
 *
 * Offline fallback uses same 3-tier priority system with SQLite data:
 *   Priority 1: Missing critical data (stale sleep, sparse mood)
 *   Priority 2: Cycle-phase-aware (period expected, fertile window, pregnancy)
 *   Priority 3: Variety fallback
 */
import type { SQLiteDatabase } from '../db/encrypted-database';

export interface WeeklyGoal {
  id?: number;
  weekStart: string;
  goalText: string;
  goalType: string;
  targetCount: number;
  currentCount: number;
  completed: boolean;
}

/** Get current week start (Monday) as ISO date */
function getWeekStart(): string {
  const now = new Date();
  const day = now.getDay();
  const diff = now.getDate() - day + (day === 0 ? -6 : 1); // Monday
  const monday = new Date(now.setDate(diff));
  return monday.toISOString().split('T')[0];
}

/** Get goals for the current week */
export async function getCurrentGoals(db: SQLiteDatabase): Promise<WeeklyGoal[]> {
  const weekStart = getWeekStart();
  const rows = await db.getAllAsync<{
    id: number;
    week_start: string;
    goal_text: string;
    goal_type: string;
    target_count: number;
    current_count: number;
    completed: number;
  }>(`SELECT * FROM weekly_goals WHERE week_start = ? ORDER BY id`, [weekStart]);

  return rows.map((row) => ({
    id: row.id,
    weekStart: row.week_start,
    goalText: row.goal_text,
    goalType: row.goal_type,
    targetCount: row.target_count,
    currentCount: row.current_count,
    completed: row.completed === 1,
  }));
}

/** Save goals from Cloud Function to SQLite */
export async function saveGoals(
  db: SQLiteDatabase,
  goals: Array<{ text: string; type: string; targetCount: number }>,
): Promise<void> {
  const weekStart = getWeekStart();

  // Don't overwrite existing goals for this week
  const existing = await db.getFirstAsync<{ count: number }>(
    `SELECT COUNT(*) as count FROM weekly_goals WHERE week_start = ?`,
    [weekStart],
  );
  if ((existing?.count ?? 0) > 0) return;

  for (const goal of goals) {
    await db.runAsync(
      `INSERT INTO weekly_goals (week_start, goal_text, goal_type, target_count, current_count, completed, created_at)
       VALUES (?, ?, ?, ?, 0, 0, datetime('now'))`,
      [weekStart, goal.text, goal.type, goal.targetCount],
    );
  }
}

/** Increment progress on a goal */
export async function incrementGoalProgress(
  db: SQLiteDatabase,
  goalId: number,
): Promise<void> {
  await db.runAsync(
    `UPDATE weekly_goals SET current_count = MIN(current_count + 1, target_count),
     completed = CASE WHEN current_count + 1 >= target_count THEN 1 ELSE 0 END
     WHERE id = ?`,
    [goalId],
  );
}

/**
 * Generate goals locally when Cloud Function is unavailable (offline fallback).
 * Uses same 3-tier priority system as the Cloud Function but reads from SQLite.
 */
export async function generateDefaultGoals(db: SQLiteDatabase): Promise<void> {
  const weekStart = getWeekStart();

  // Don't overwrite existing goals
  const existing = await db.getFirstAsync<{ count: number }>(
    `SELECT COUNT(*) as count FROM weekly_goals WHERE week_start = ?`,
    [weekStart],
  );
  if ((existing?.count ?? 0) > 0) return;

  const now = new Date();
  const threeDaysAgo = new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000)
    .toISOString()
    .split('T')[0];
  const sevenDaysAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000)
    .toISOString()
    .split('T')[0];

  // Check user state from SQLite
  const totalCyclesRow = await db.getFirstAsync<{ count: number }>(
    `SELECT COUNT(*) as count FROM cycles`,
  );
  const totalCycles = totalCyclesRow?.count ?? 0;

  const totalMoodRow = await db.getFirstAsync<{ count: number }>(
    `SELECT COUNT(*) as count FROM daily_logs WHERE mood_level IS NOT NULL`,
  );
  const totalMoodLogs = totalMoodRow?.count ?? 0;
  const isNewUser = totalCycles === 0 && totalMoodLogs === 0;

  // Check pregnancy status
  const profileRow = await db.getFirstAsync<{ pregnancy_status: string | null }>(
    `SELECT pregnancy_status FROM user_profile WHERE id = 1`,
  );
  const isPregnant = profileRow?.pregnancy_status === 'pregnant';

  const p1: Array<{ text: string; type: string; targetCount: number }> = [];
  const p2: Array<{ text: string; type: string; targetCount: number }> = [];
  const p3: Array<{ text: string; type: string; targetCount: number }> = [];

  // ── Priority 1: Missing critical data (only for returning users) ──
  if (!isNewUser) {
    const recentSleep = await db.getFirstAsync<{ count: number }>(
      `SELECT COUNT(*) as count FROM daily_logs WHERE log_date >= ? AND sleep_hours IS NOT NULL`,
      [threeDaysAgo],
    );
    if ((recentSleep?.count ?? 0) === 0 && totalMoodLogs > 0) {
      p1.push({ text: 'Tell Maa about your sleep twice', type: 'sleep', targetCount: 2 });
    }

    const recentMood = await db.getFirstAsync<{ count: number }>(
      `SELECT COUNT(*) as count FROM daily_logs WHERE log_date >= ? AND mood_level IS NOT NULL`,
      [sevenDaysAgo],
    );
    if ((recentMood?.count ?? 0) < 2) {
      p1.push({ text: 'Check in with your mood 3 times', type: 'mood', targetCount: 3 });
    }
  }

  // ── Priority 2: Cycle-phase-aware / Pregnancy / New user ──
  if (isPregnant) {
    p2.push({ text: 'Tell Maa how you are feeling today', type: 'wellness', targetCount: 1 });
    p2.push({ text: 'Track any new symptoms this week', type: 'symptom', targetCount: 2 });
  } else if (isNewUser) {
    p2.push({ text: 'Tell Maa when your next period starts', type: 'cycle', targetCount: 1 });
    p2.push({ text: 'Have a conversation with Maa', type: 'voice', targetCount: 1 });
  } else {
    // Get last cycle for phase detection
    const lastCycle = await db.getFirstAsync<{ start_date: string }>(
      `SELECT start_date FROM cycles ORDER BY start_date DESC LIMIT 1`,
    );
    const profileData = await db.getFirstAsync<{ cycle_length_avg: number | null }>(
      `SELECT cycle_length_avg FROM user_profile WHERE id = 1`,
    );
    const avgCycleLength = profileData?.cycle_length_avg ?? 28;

    if (lastCycle) {
      const lastPeriodMs = new Date(lastCycle.start_date).getTime();
      const daysSince = Math.floor((now.getTime() - lastPeriodMs) / (24 * 60 * 60 * 1000));
      const daysUntilNext = avgCycleLength - daysSince;
      const isInFertileWindow = daysSince >= 10 && daysSince <= 16;

      if (daysUntilNext >= 0 && daysUntilNext <= 7) {
        p2.push({ text: 'Log when your period starts', type: 'cycle', targetCount: 1 });
      } else if (isInFertileWindow) {
        p2.push({ text: 'Track any ovulation symptoms', type: 'symptom', targetCount: 2 });
      } else {
        p2.push({ text: 'Share how you are feeling 3 times', type: 'mood', targetCount: 3 });
      }
    } else {
      p2.push({ text: 'Tell Maa when your next period starts', type: 'cycle', targetCount: 1 });
    }
  }

  // ── Priority 3: Variety ──
  p3.push(
    { text: 'Have a conversation with Maa', type: 'voice', targetCount: 1 },
    { text: 'Tell Maa about your energy levels', type: 'energy', targetCount: 1 },
    { text: 'Talk to Maa 3 times this week', type: 'voice_3x', targetCount: 3 },
  );

  // ── Assemble: P2 always gets at least 1 slot ──
  const goals: Array<{ text: string; type: string; targetCount: number }> = [];
  const usedTypes = new Set<string>();

  function addGoal(g: { text: string; type: string; targetCount: number }): boolean {
    if (usedTypes.has(g.type)) return false;
    goals.push(g);
    usedTypes.add(g.type);
    return true;
  }

  // P2 first (at least 1)
  if (p2.length > 0) addGoal(p2[0]);

  // P1 (max 1)
  for (const g of p1) {
    if (goals.length >= 3) break;
    if (goals.length < 2) addGoal(g);
  }

  // P2 extras
  for (let i = 1; i < p2.length; i++) {
    if (goals.length >= 3) break;
    addGoal(p2[i]);
  }

  // P3 fill
  for (const g of p3) {
    if (goals.length >= 3) break;
    addGoal(g);
  }

  await saveGoals(db, goals.slice(0, 3));
}
